### ISSUE TITLE
Next Step

### ISSUE THREAD

**Issue by gvillalta99** [SunsetRiders/nodejs-scaffold#1]
@jmcoimbra thank you for bootstraping this project!

What is the next step?

From the whiteboard:
- [x] [express.js](http://expressjs.com/)
- [x] [SASS](http://sass-lang.com/)
- [x] [Grunt](http://gruntjs.com/) or [Gulp](http://gulpjs.com/)
- [x] [JQuery](https://jquery.com/)
- [x] [Mocha](https://mochajs.org/)

Who is responsible for what?
Any thoughts @habner, @msughawara, @marciodaitan, @wellington-barbosa-daitan, @jmcoimbra ?

**Comment by jmcoimbra** [comment]
Mocha -> Márcio
Sass + JQuery + Grunt -> Habner
express -> Habner, Gustavo and me

**Comment by gvillalta99** [comment]
@habner has done this on  0125ffd , already in the master branch.
